apiVersion: apps/v1
kind: Deployment

metadata:
  name: blog-api
  namespace: blog-app

spec:
  replicas: 2

  selector:
    matchLabels:
      app: blog-api

  template:
    metadata:
      labels:
        app: blog-api

    spec:
      containers:
        - name: blog-api
          image: spandan735/blog-app:latest
          imagePullPolicy: Always

          ports:
            - containerPort: 8000

          envFrom:
            - configMapRef:
                name: blog-api-config

          env:
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: blog-api-secret
                  key: JWT_KEY

          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 15
            periodSeconds: 10

          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 5

          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"

            limits:
              cpu: "500m"
              memory: "512Mi"